[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
nohash-hasher = "0.2.0"
rayon = "1.10.0"
regex = "1.11.1"
rustc-hash = "2.1.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "solution_benchmarks"
harness = false
